version: 2.1

jobs:
  build-jdk8:
    docker:
      - image: cimg/openjdk:8.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline -pl StaffPlusAPI,staff-api -am
      - save_cache:
          paths:
            - ~/.m2
          key: v1-deps-{{ checksum "pom.xml" }}
      - run: mvn clean package -pl StaffPlusAPI,staff-api -am
      - run: mvn test -pl staff-api -am

  build-jdk17:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "staff-modern-core/pom.xml" }}
      - run: mvn dependency:go-offline -pl staff-api,staff-modern-core -am
      - save_cache:
          paths:
            - ~/.m2
          key: v2-deps-{{ checksum "staff-modern-core/pom.xml" }}
      - run: mvn clean package -pl staff-api,staff-modern-core -am
      - run: mvn test -pl staff-api,staff-modern-core -am

workflows:
  version: 2
  build-all:
    jobs:
      - build-jdk8
      - build-jdk17